// src/vehicleData.js
const vehicleData = [
  {
    id: 'delica-97',
    title: '1997 Mitsubishi Delica Space Gear',
    image: '/images/delica-1997.png',
    status: 'Available',
    year: 1997,
    make: 'Mitsubishi',
    type: 'Van',
    specs: '3.0L Gasoline | Crystal Lite Roof | 4WD',
    price: '$16,900',
    mileage: '122,000 km',
  },
  {
    id: 'hiace-96',
    title: '1996 Toyota Hiace Super Custom',
    image: '/images/hiace-1998.png',
    status: 'Sold',
    year: 1998,
    make: 'Toyota',
    type: 'Van',
    specs: '3.0L Diesel Turbo | 4WD | Automatic',
    price: '$19,800',
    mileage: '138,000 km',
  },
  {
    id: 'grand-hiace-99',
    title: '1999 Toyota Grand Hiace',
    image: '/images/grand_hiace-1999.png',
    status: 'Available',
    year: 1999,
    make: 'Toyota',
    type: 'Van',
    specs: '3.4L Gasoline | 4WD | Automatic',
    price: '$22,800',
    mileage: '121,000 km',
  },
  {
    id: 'evo-vi-99',
    title: '1999 Mitsubishi Evolution VI',
    image: '/images/evo_vi_gsr-1999.png',
    status: 'Sold',
    year: 1999,
    make: 'Mitsubishi',
    type: 'Sports Car',
    specs: '2.0L Turbo Gasoline | 4WD | Manual',
    price: '$33,000',
    mileage: '89,000 km',
  },
    {
    id: 'JB470-96',
    title: '1996 Mitsubishi Delica JB470',
    image: '/images/JB470-96.png',
    status: 'Available',
    year: 1996,
    make: 'Mitsubishi',
    type: 'Camper',
    specs: 'Vantech Fiberglass Camper | 4WD | Manual',
    price: '$34,500',
    mileage: '151,000 km',
  },
    {
    id: 'hiace-alamo-96',
    title: '1996 Toyota Hiace Alamo',
    image: '/images/hiace-alamo-96.png',
    status: 'Sold',
    year: 1996,
    make: 'Toyota',
    type: 'Camper',
    specs: '2.8L Diesel | 2WD | Auto',
    price: '$33,000',
    mileage: '84,000 km',
  },
      {
    id: 'astro-camper-96',
    title: '1996 Chevy Astro Camper',
    image: '/images/astro-camper-96.png',
    status: 'Sold',
    year: 1996,
    make: 'Chevy',
    type: 'Camper',
    specs: '4.3L Gasoline | 4WD | Auto',
    price: '$26,700',
    mileage: '23,000 km',
  },

];

export default vehicleData;
